### ISSUE TITLE
S3 suport for azure blob storage

### ISSUE THREAD

**Issue by Louis-wr** [DataverseNO/dataverse#36]
Minio is currently connected to Azure blob 
Minio emulate an endpoint on the Vm, Traefik needs to be configured to have the minio endpoint accessible inside the dataverse container.
Possibility of using minio docker

**Comment by philippconzett** [comment]
Things we need to test:
- [] Upload of larger files via http

**Comment by rolfande** [comment]
I guess this is solved as we went for S3 Cloudian and azure was lacking support for S3 on their blob storage.
